"""
gemini_client.py

This file connects our StudyMate AI Agent with the Gemini API.

Responsibilities:
- Send study notes to Gemini.
- Ask Gemini to create a summary.
- Ask Gemini to create quiz questions and answers.
- Ask Gemini to detect hard and easy concepts.
"""

from google import genai

from src.config import Config


class GeminiClient:
    """
    GeminiClient is responsible for all AI-generated content.

    The rest of the project should not directly talk to Gemini.
    Instead, the agent will call this class.
    """

    def __init__(self):
        """
        Creates a Gemini client using the API key from the .env file.
        """

        Config.validate()

        self.client = genai.Client(api_key=Config.GEMINI_API_KEY)
        self.model_name = Config.GEMINI_MODEL_NAME

    def _generate_text(self, prompt: str) -> str:
        """
        Sends a prompt to Gemini and returns the generated text.

        Args:
            prompt: The instruction/question sent to Gemini.

        Returns:
            Gemini's text response.
        """

        response = self.client.models.generate_content(
            model=self.model_name,
            contents=prompt
        )

        if not response.text:
            return "No response generated by Gemini."

        return response.text.strip()

    def generate_summary(self, notes: str) -> str:
        """
        Generates a beginner-friendly summary from study notes.
        """

        prompt = f"""
You are StudyMate AI, a helpful study assistant.

Your task:
Read the study notes below and create a clear beginner-friendly summary.

Rules:
- Use simple language.
- Use bullet points.
- Keep the explanation useful for revision.
- Do not add unrelated information.

Study notes:
{notes}
"""

        return self._generate_text(prompt)

    def generate_quiz(self, notes: str) -> str:
        """
        Generates quiz questions and answers from study notes.
        """

        prompt = f"""
You are StudyMate AI, a quiz generator.

Create a quiz from the study notes below.

Include:
1. 5 multiple-choice questions
2. 3 true/false questions
3. 2 short-answer questions
4. Answer key at the end

Rules:
- Questions must be based only on the given notes.
- Use clear and simple language.
- Mark the answer key clearly.

Study notes:
{notes}
"""

        return self._generate_text(prompt)

    def detect_concepts(self, notes: str) -> str:
        """
        Detects hard and easy concepts from study notes.
        """

        prompt = f"""
You are StudyMate AI, a learning support assistant.

Analyze the study notes below.

Return:
1. Easy concepts
2. Hard concepts
3. Why the hard concepts may be difficult
4. Revision advice for the student

Rules:
- Use simple language.
- Use headings and bullet points.
- Stay based on the notes.

Study notes:
{notes}
"""

        return self._generate_text(prompt)